highlighter: pygments
relative_permalinks: false
gauges_id: 503c5af6613f5d0f19000027
base_url: jekyll-site
permalink: /news/:year/:month/:day/:title/
excerpt_separator: noifniof3nioaniof3nioafafinoafnoif
repository: https://github.com/wolfe-pack/wolfe
help_url: https://github.com/wolfe-pack/wolfe
